Repository BaseballCV/BaseballCV, pull requests merged in 2024-11, with the labels that each got.

#34 Fix Name Bug in Video Download from Scraper
  scripts/savant_scraper.py
Labels: bug

#38 37 update main readme to generate own dataset using tools
  README.md
  scripts/README.md
Labels: enhancement

#42 fix scraper only scraping home batting and improve scraper usability
  scripts/savant_scraper.py
Labels: bug

#50 Adding Florence 2 notebook, updating READMEs to accomodate this model…
  README.md
  notebooks/Florence_2_example.ipynb
  notebooks/README.md
  scripts/load_tools.py
Labels: documentation

#51 26 create streamlit app designed for open source annotations
  .gitignore
  models/YOLO/ball_tracking/model_training_info/events.out.tfevents.1728083240.9006c419a657.476.1
  models/YOLO/glove_tracking/model_training_info/events.out.tfevents.1728404434.6b308c95571b.30.0
  requirements.txt
  scripts/__init__.py
  scripts/load_tools.py
  streamlit/annotation_app/Dockerfile
  streamlit/annotation_app/app.py
  streamlit/annotation_app/app_utils/__init__.py
  streamlit/annotation_app/app_utils/annotation_manager.py
  streamlit/annotation_app/app_utils/app_pages.py
  streamlit/annotation_app/app_utils/default_tools.py
  streamlit/annotation_app/app_utils/file_tools.py
  streamlit/annotation_app/app_utils/image_manager.py
  streamlit/annotation_app/app_utils/model_manager.py
  streamlit/annotation_app/app_utils/s3.py
  streamlit/annotation_app/app_utils/task_manager.py
  streamlit/annotation_app/docker-compose.yml
Labels: enhancement
