Repository BaseballCV/BaseballCV, pull requests merged in 2025-03, with the labels that each got.

#104 98 upgrade pytests for current model offerings and package
  .github/workflows/build.yml
  .github/workflows/discord_package.yml
  .github/workflows/discord_pr.yml
  .github/workflows/pypi-publish.yml
  .github/workflows/pytest.yml
  .gitignore
  README.md
  baseballcv/__init__.py
  baseballcv/datasets/formats/datasets_coco_detection.py
  baseballcv/functions/dataset_tools.py
  baseballcv/functions/load_tools.py
  baseballcv/model/utils/model_function_utils.py
  baseballcv/model/vlm/florence2/florence2.py
  datasets/JSONL/amateur_hitter_pitcher_jsonl.txt
  docs/datasets/index.md
  pyproject.toml
  requirements.txt
  tests/conftest.py
  tests/test_api/test_baseballcv_api.py
  tests/test_dataset_tools.py
  tests/test_datasets/test_datasets_coco_detection.py
  tests/test_datasets/test_datasets_jsonl_detection.py
  tests/test_datasets/test_datasets_processor.py
  tests/test_functions/test_baseball_tools.py
  tests/test_functions/test_dataset_tools.py
  tests/test_functions/test_imports.py
  tests/test_functions/test_load_tools.py
  tests/test_functions/test_savant_scraper.py
  tests/test_load_tools.py
  tests/test_model/test_detr.py
  tests/test_model/test_florence2.py
  tests/test_model/test_model_function_utils.py
  tests/test_model/test_model_logger.py
  tests/test_model/test_paligemma.py
  tests/test_model/test_yolov9.py
  tests/test_savant_scraper.py
Labels: enhancement, testing

#106 102 add functionality for hf and international datasets models
  README.md
  baseballcv/functions/dataset_tools.py
  baseballcv/functions/load_tools.py
  models/README.md
  models/YOLOv9/homeplate_tracking/model_training_info/F1_curve.png
  models/YOLOv9/homeplate_tracking/model_training_info/PR_curve.png
  models/YOLOv9/homeplate_tracking/model_training_info/P_curve.png
  models/YOLOv9/homeplate_tracking/model_training_info/R_curve.png
  models/YOLOv9/homeplate_tracking/model_training_info/confusion_matrix.png
  models/YOLOv9/homeplate_tracking/model_training_info/hyp.yaml
  models/YOLOv9/homeplate_tracking/model_training_info/labels.jpg
  models/YOLOv9/homeplate_tracking/model_training_info/labels_correlogram.jpg
  models/YOLOv9/homeplate_tracking/model_training_info/opt.yaml
  models/YOLOv9/homeplate_tracking/model_training_info/results.csv
  models/YOLOv9/homeplate_tracking/model_training_info/results.png
  models/YOLOv9/homeplate_tracking/model_training_info/train_batch0.jpg
  models/YOLOv9/homeplate_tracking/model_training_info/train_batch1.jpg
  models/YOLOv9/homeplate_tracking/model_training_info/train_batch2.jpg
  models/YOLOv9/homeplate_tracking/model_training_info/val_batch0_labels.jpg
  models/YOLOv9/homeplate_tracking/model_training_info/val_batch0_pred.jpg
  models/YOLOv9/homeplate_tracking/model_training_info/val_batch1_labels.jpg
  models/YOLOv9/homeplate_tracking/model_training_info/val_batch1_pred.jpg
  models/YOLOv9/homeplate_tracking/model_training_info/val_batch2_labels.jpg
  models/YOLOv9/homeplate_tracking/model_training_info/val_batch2_pred.jpg
  models/YOLOv9/homeplate_tracking/model_weights/homeplate_tracking.txt
Labels: documentation, enhancement, model, dataset

#108 Add BaseballCV Logger Class
  .github/workflows/pytest.yml
  baseballcv/datasets/formats/datasets_coco_detection.py
  baseballcv/datasets/formats/datasets_jsonl_detection.py
  baseballcv/functions/baseball_tools.py
  baseballcv/functions/dataset_tools.py
  baseballcv/functions/load_tools.py
  baseballcv/functions/savant_scraper.py
  baseballcv/functions/utils/distance_to_zone.py
  baseballcv/model/od/detr/detr.py
  baseballcv/model/od/yolo/yolo.py
  baseballcv/model/utils/__init__.py
  baseballcv/model/utils/model_function_utils.py
  baseballcv/model/utils/model_logger.py
  baseballcv/model/vlm/florence2/florence2.py
  baseballcv/model/vlm/paligemma2/paligemma2.py
  baseballcv/utilities/__init__.py
  baseballcv/utilities/dependencies/git_dependency_installer.py
  baseballcv/utilities/logger/baseballcv_logger.py
  baseballcv/utils/__init__.py
  baseballcv/utils/git_dependency_installer.py
  tests/conftest.py
  tests/test_model/test_model_function_utils.py
  tests/test_model/test_model_logger.py
  tests/test_model/test_paligemma.py
  tests/test_utilities/test_baseballcv_logger.py
Labels: enhancement

#112 105 optimize baseball savant video scraper for faster scraping times
  baseballcv/README.md
  baseballcv/functions/README.md
  baseballcv/functions/baseball_tools.py
  baseballcv/functions/dataset_tools.py
  baseballcv/functions/savant_scraper.py
  baseballcv/functions/utils/distance_to_zone.py
  baseballcv/functions/utils/savant_utils/__init__.py
  baseballcv/functions/utils/savant_utils/crawler.py
  baseballcv/functions/utils/savant_utils/gameday.py
  docs/best-practices/index.md
  docs/faq/index.md
  docs/repository-structure/index.md
  tests/conftest.py
  tests/test_functions/test_baseball_tools.py
  tests/test_functions/test_dataset_tools.py
  tests/test_functions/test_imports.py
  tests/test_functions/test_savant_scraper.py
  tests/test_model/test_rfdetr.py
Labels: enhancement, testing

#113 Edit Automated Annotation to include AutoDistill
  README.md
  baseballcv/functions/README.md
  baseballcv/functions/dataset_tools.py
  docs/datasets/index.md
  docs/using-repository/training-pipeline.md
  pyproject.toml
  requirements.txt
  tests/test_functions/test_dataset_tools.py
Labels: enhancement, dataset
