Repository BaseballCV/BaseballCV, pull requests merged in 2025-05, with the labels that each got.

#127 Update AutoDistill to Batch Image Processing
  baseballcv/functions/README.md
  baseballcv/functions/dataset_tools.py
  tests/test_functions/test_dataset_tools.py
Labels: bug, documentation, enhancement

#129 Update LoadTools to Handle Different Data Types
  .gitignore
  README.md
  baseballcv/functions/load_tools.py
  baseballcv/functions/savant_scraper.py
  docs/datasets/index.md
  streamlit/gemini_annotating_app/README.md
  streamlit/gemini_annotating_app/app.py
  streamlit/gemini_annotating_app/app_assets/baseballcvlogo.png
  streamlit/gemini_annotating_app/app_utils/data_downloader.py
  streamlit/gemini_annotating_app/app_utils/detection_processor.py
  streamlit/inference_app/app.py
  streamlit/inference_app/app_utils/__init__.py
  streamlit/inference_app/app_utils/dataset_creation.py
  streamlit/inference_app/app_utils/file_manager.py
  streamlit/inference_app/app_utils/inference_models.py
  streamlit/inference_app/requirements.txt
Labels: documentation, enhancement, dataset

#131 Address Messages and Errors on Import
  README.md
  baseballcv/README.md
  baseballcv/__init__.py
  baseballcv/datasets/__init__.py
  baseballcv/functions/__init__.py
  baseballcv/functions/dataset_tools.py
  baseballcv/model/__init__.py
  baseballcv/model/od/yolo/yolo.py
  baseballcv/utilities/__init__.py
  baseballcv/utilities/dependencies/git_dependency_installer.py
  tests/test_utilities/test_git_dependency_installer.py
Labels: bug, enhancement

#139 Create Streamlit App Designed for Inference Testing
  .gitignore
  README.md
  assets/baseballcvlogo.png
  baseballcv/README.md
  baseballcv/functions/load_tools.py
  baseballcv/model/od/detr/rfdetr.py
  baseballcv/model/od/yolo/yolo.py
  baseballcv/model/utils/model_function_utils.py
  docs/index.md
  poetry.lock
  pyproject.toml
  streamlit/README.md
  streamlit/gemini_annotating_app/README.md
  streamlit/gemini_annotating_app/requirements.txt
  streamlit/inference_app/README.md
  streamlit/inference_app/app.py
  streamlit/inference_app/app_utils/__init__.py
  streamlit/inference_app/app_utils/dataset_creation.py
  streamlit/inference_app/app_utils/file_manager.py
  streamlit/inference_app/app_utils/inference_models.py
  streamlit/inference_app/requirements.txt
Labels: documentation, enhancement

#140 138 update rfdetr w correct functionality version and tests
  README.md
  baseballcv/README.md
  baseballcv/__init__.py
  baseballcv/model/README.md
  baseballcv/model/od/detr/rfdetr.py
  docs/repository-structure/index.md
  models/od/RFDETR/rubber_home/model_weights/rfdetr_baseball_rubber_home_v1.txt
  pyproject.toml
  tests/test_model/test_rfdetr.py
Labels: bug
